name: Trigger Selected Players Creation

on:
  push:
    branches:
      - master

jobs:
  create_players:
    runs-on: ubuntu-latest
    
    steps:
    - name: Send HTTP request
      run: curl -X POST ${{ secrets.BACKEND_URL }}
