name: Select correct player for the day

on:
  push:
    branches:
      - master
  workflow_dispatch:
    

jobs:
  create_players:
    runs-on: ubuntu-latest
    
    steps:
    - name: Send HTTP request
      run: curl -X POST ${{ secrets.BACKEND_URL }}
      
