name: Test Endpoint

on:
  push:
    branches:
      - main

jobs:
  test_endpoint:
    runs-on: ubuntu-latest

    steps:
      - name: Check endpoint availability
        run: |
          response_code=$(curl -s -o /dev/null -w "%{http_code}" https://luigi-backend-7f709e978d15.herokuapp.com/players/)
          if [ $response_code -eq 200 ]; then
            echo "Endpoint is accessible"
          else
            echo "Endpoint is not accessible, HTTP status code: $response_code"
            exit 1
          fi
